<?php

namespace Database\Seeders;

use App\Models\BillingPlan;
use Illuminate\Database\Seeder;

class BillingPlansSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Starter',
                'slug' => 'starter',
                'tagline' => 'Perfect for small schools',
                'description' => 'Everything you need to get started with school management',
                'price_amount' => 79.00,
                'price_display' => null,
                'currency' => 'USD',
                'billing_period' => 'month',
                'billing_period_label' => '/month',
                'cta_label' => 'Get Started',
                'is_highlighted' => false,
                'is_active' => true,
                'position' => 1,
                'features' => [
                    'Up to 100 students',
                    'Basic attendance tracking',
                    'Grade management',
                    'Parent portal',
                    'Email support',
                    '5 GB storage',
                ],
                'modules' => [
                    'students' => true,
                    'classes' => true,
                    'subjects' => true,
                    'attendance' => true,
                    'grades' => true,
                    'reports' => true,
                    'parents' => true,
                    'finance' => false,
                    'messaging' => false,
                    'online_exams' => false,
                    'hr' => false,
                    'library' => false,
                    'inventory' => false,
                    'transport' => false,
                    'hostel' => false,
                    'api_access' => false,
                ],
                'limits' => [
                    'students' => 100,
                    'storage_gb' => 5,
                    'users' => 5,
                ],
            ],
            [
                'name' => 'Growth',
                'slug' => 'growth',
                'tagline' => 'For growing institutions',
                'description' => 'Advanced features for expanding schools',
                'price_amount' => 129.00,
                'price_display' => null,
                'currency' => 'USD',
                'billing_period' => 'month',
                'billing_period_label' => '/month',
                'cta_label' => 'Start Free Trial',
                'is_highlighted' => false,
                'is_active' => true,
                'position' => 2,
                'features' => [
                    'Up to 500 students',
                    'Advanced attendance & biometrics',
                    'Online exams & assessments',
                    'Financial management',
                    'SMS & WhatsApp notifications',
                    'Priority support',
                    '25 GB storage',
                ],
                'modules' => [
                    'students' => true,
                    'classes' => true,
                    'subjects' => true,
                    'attendance' => true,
                    'grades' => true,
                    'reports' => true,
                    'parents' => true,
                    'finance' => true,
                    'messaging' => true,
                    'online_exams' => true,
                    'events' => true,
                    'hr' => false,
                    'library' => false,
                    'inventory' => false,
                    'transport' => false,
                    'hostel' => false,
                    'api_access' => false,
                ],
                'limits' => [
                    'students' => 500,
                    'storage_gb' => 25,
                    'users' => 20,
                ],
            ],
            [
                'name' => 'Premium',
                'slug' => 'premium',
                'tagline' => 'Most Popular',
                'description' => 'Complete school management solution',
                'price_amount' => 189.00,
                'price_display' => null,
                'currency' => 'USD',
                'billing_period' => 'month',
                'billing_period_label' => '/month',
                'cta_label' => 'Start Free Trial',
                'is_highlighted' => true,
                'is_active' => true,
                'position' => 3,
                'features' => [
                    'Up to 2,000 students',
                    'All Growth features',
                    'Library management',
                    'HR & Payroll',
                    'Custom domain',
                    'API access',
                    'Dedicated account manager',
                    '100 GB storage',
                ],
                'modules' => [
                    'students' => true,
                    'classes' => true,
                    'subjects' => true,
                    'attendance' => true,
                    'grades' => true,
                    'reports' => true,
                    'parents' => true,
                    'finance' => true,
                    'messaging' => true,
                    'online_exams' => true,
                    'events' => true,
                    'hr' => true,
                    'library' => true,
                    'inventory' => true,
                    'transport' => true,
                    'hostel' => true,
                    'api_access' => true,
                    'custom_domain' => true,
                ],
                'limits' => [
                    'students' => 2000,
                    'storage_gb' => 100,
                    'users' => 50,
                ],
            ],
            [
                'name' => 'Enterprise',
                'slug' => 'enterprise',
                'tagline' => 'For large institutions',
                'description' => 'Tailored solutions for universities and school networks',
                'price_amount' => null,
                'price_display' => 'Custom',
                'currency' => 'USD',
                'billing_period' => null,
                'billing_period_label' => null,
                'cta_label' => 'Contact Sales',
                'is_highlighted' => false,
                'is_active' => true,
                'position' => 4,
                'features' => [
                    'Unlimited students',
                    'All Premium features',
                    'Multi-campus support',
                    'Custom integrations',
                    'On-premise deployment option',
                    'SLA guarantee',
                    '24/7 phone support',
                    'Unlimited storage',
                ],
                'modules' => [
                    'students' => true,
                    'classes' => true,
                    'subjects' => true,
                    'attendance' => true,
                    'grades' => true,
                    'reports' => true,
                    'parents' => true,
                    'finance' => true,
                    'messaging' => true,
                    'online_exams' => true,
                    'events' => true,
                    'hr' => true,
                    'library' => true,
                    'inventory' => true,
                    'transport' => true,
                    'hostel' => true,
                    'api_access' => true,
                    'custom_domain' => true,
                    'multi_campus' => true,
                    'sso' => true,
                    'audit_logs' => true,
                ],
                'limits' => [
                    'students' => -1, // Unlimited
                    'storage_gb' => -1,
                    'users' => -1,
                ],
            ],
        ];

        foreach ($plans as $plan) {
            BillingPlan::updateOrCreate(
                ['slug' => $plan['slug']],
                $plan
            );
        }

        $this->command->info('✓ Created 4 billing plans with modules and limits');
    }
}
