<?php

namespace App\Http\Controllers\Tenant\Modules\HumanResource;

use App\Http\Controllers\Controller;
use App\Models\Employee;
use App\Services\Media\ImageService;
use App\Services\Media\AvatarGenerator;
use App\Http\Requests\EmployeeRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class EmployeesController extends Controller
{
    public function index(): View
    {
        $employees = Employee::all();
        return view('tenant.modules.human_resource.employees.index', compact('employees'));
    }

    public function create(): View
    {
        $this->authorize('create', Employee::class);
        $departments = \App\Models\Department::all();
        $positions = \App\Models\Position::all();
        $salary_scales = \App\Models\SalaryScale::all();
        return view('tenant.modules.human_resource.employees.create', compact('departments', 'positions', 'salary_scales'));
    }

    public function store(EmployeeRequest $request, ImageService $imageService, AvatarGenerator $avatarGenerator): RedirectResponse
    {
        $this->authorize('create', Employee::class);
        $data = $request->validated();

        // Handle optional passport photo upload with resizing
        if ($request->hasFile('passport_photo')) {
            $data['photo_path'] = $imageService->processPassportPhoto($request->file('passport_photo'));
        }

        // Generate deterministic phone if blank (Uganda format +2567xxxxxxx)
        if (empty($data['phone'])) {
            $data['phone'] = '+2567' . str_pad((string)random_int(1000000, 9999999), 7, '0', STR_PAD_LEFT);
        }

        // Additional duplicate check (belt and suspenders approach)
        if ($data['email']) {
            $existingEmployee = Employee::where('email', $data['email'])->first();
            if ($existingEmployee) {
                return redirect()->back()
                    ->withInput()
                    ->withErrors(['email' => 'This email address is already in use by another employee.']);
            }
        }

        // Check for duplicate name in same department
        $existingName = Employee::where('department_id', $data['department_id'])
            ->where('first_name', $data['first_name'])
            ->where('last_name', $data['last_name'])
            ->first();

        if ($existingName) {
            return redirect()->back()
                ->withInput()
                ->withErrors(['first_name' => 'An employee with this name already exists in the selected department.']);
        }

        // Remove employee_number if present (will be auto-generated by observer)
        unset($data['employee_number']);
        
        // Create employee (observer will auto-generate employee_number)
        $employee = Employee::create($data);

        // If still no photo, generate avatar
        if (empty($employee->photo_path)) {
            $employee->photo_path = $avatarGenerator->generate($employee->first_name, $employee->last_name);
            $employee->save();
        }

        // Link or create user if email present and not already linked
        if (!empty($employee->email) && empty($employee->user_id)) {
            $userModel = \App\Models\User::where('email', $employee->email)->first();
            if (!$userModel) {
                $userModel = \App\Models\User::create([
                    'name' => $employee->first_name . ' ' . $employee->last_name,
                    'email' => $employee->email,
                    'password' => bcrypt(str()->random(16)),
                ]);
            }
            $employee->user_id = $userModel->id;
            $employee->save();
        }

        return redirect()->route('tenant.modules.human_resources.employees.index')
            ->with('success', 'Employee created successfully with ID: ' . $employee->employee_number);
    }

    public function show(Employee $employee): View
    {
        $this->authorize('view', $employee);
        
        // Load payroll data
        $recentPayrolls = $employee->payrollRecords()
            ->with(['approvedBy', 'paidBy'])
            ->orderBy('payment_date', 'desc')
            ->limit(12)
            ->get();

        // Year-to-date calculations (current year)
        $currentYear = now()->year;
        $ytdPayrolls = $employee->payrollRecords()
            ->where('period_year', $currentYear)
            ->where('status', 'paid')
            ->get();

        $ytdData = [
            'total_gross' => $ytdPayrolls->sum('gross_salary'),
            'total_net' => $ytdPayrolls->sum('net_salary'),
            'total_deductions' => $ytdPayrolls->sum('total_deductions'),
            'total_tax' => $ytdPayrolls->sum('tax_deduction'),
            'total_nssf' => $ytdPayrolls->sum('nssf_deduction'),
            'total_bonuses' => $ytdPayrolls->sum('bonuses'),
            'months_paid' => $ytdPayrolls->count(),
        ];

        // Latest salary information
        $latestPayroll = $recentPayrolls->first();
        
        // Salary summary
        $salarySummary = [
            'basic_salary' => $latestPayroll->basic_salary ?? ($employee->basic_salary ?? 0),
            'average_gross' => $ytdPayrolls->avg('gross_salary') ?? 0,
            'average_net' => $ytdPayrolls->avg('net_salary') ?? 0,
            'last_payment_date' => $latestPayroll->payment_date ?? null,
            'next_payment_due' => $latestPayroll ? $latestPayroll->payment_date->addMonth() : null,
        ];

        return view('tenant.modules.human_resource.employees.show', compact(
            'employee',
            'recentPayrolls',
            'ytdData',
            'salarySummary'
        ));
    }

    public function edit(Employee $employee): View
    {
        $this->authorize('update', $employee);
        $departments = \App\Models\Department::all();
        $positions = \App\Models\Position::all();
        $salary_scales = \App\Models\SalaryScale::all();
        return view('tenant.modules.human_resource.employees.edit', compact('employee', 'departments', 'positions', 'salary_scales'));
    }

    public function update(EmployeeRequest $request, Employee $employee, ImageService $imageService, AvatarGenerator $avatarGenerator): RedirectResponse
    {
        $this->authorize('update', $employee);
        $data = $request->validated();

        if ($request->hasFile('passport_photo')) {
            $data['photo_path'] = $imageService->processPassportPhoto($request->file('passport_photo'));
        }

        if (empty($data['phone']) && !$employee->phone) {
            $data['phone'] = '+2567' . str_pad((string)random_int(1000000, 9999999), 7, '0', STR_PAD_LEFT);
        }

        // Additional duplicate check for email (excluding current employee)
        if ($data['email'] && $data['email'] !== $employee->email) {
            $existingEmployee = Employee::where('email', $data['email'])
                ->where('id', '!=', $employee->id)
                ->first();
            if ($existingEmployee) {
                return redirect()->back()
                    ->withInput()
                    ->withErrors(['email' => 'This email address is already in use by another employee.']);
            }
        }

        // Check for duplicate name in same department (excluding current employee)
        $existingName = Employee::where('department_id', $data['department_id'])
            ->where('first_name', $data['first_name'])
            ->where('last_name', $data['last_name'])
            ->where('id', '!=', $employee->id)
            ->first();

        if ($existingName) {
            return redirect()->back()
                ->withInput()
                ->withErrors(['first_name' => 'An employee with this name already exists in the selected department.']);
        }

        $employee->update($data);

        if (empty($employee->photo_path)) {
            $employee->photo_path = $avatarGenerator->generate($employee->first_name, $employee->last_name);
            $employee->save();
        }

        if (!empty($employee->email) && empty($employee->user_id)) {
            $userModel = \App\Models\User::where('email', $employee->email)->first();
            if (!$userModel) {
                $userModel = \App\Models\User::create([
                    'name' => $employee->first_name . ' ' . $employee->last_name,
                    'email' => $employee->email,
                    'password' => bcrypt(str()->random(16)),
                ]);
            }
            $employee->user_id = $userModel->id;
            $employee->save();
        }
        return redirect()->route('tenant.modules.human_resources.employees.index')->with('success', 'Employee updated successfully.');
    }

    public function createUserAccount(Employee $employee, \Illuminate\Http\Request $request): RedirectResponse
    {
        // Check if employee already has a user account
        if ($employee->user_id) {
            return redirect()->back()
                ->with('error', 'This employee already has a user account.');
        }

        // Validate that employee has an email
        if (empty($employee->email)) {
            return redirect()->back()
                ->with('error', 'Cannot create user account: Employee does not have an email address.');
        }

        // Validate role
        $request->validate([
            'role' => 'required|string|in:Admin,Staff,Teacher',
        ]);

        try {
            // Check if a user with this email already exists
            $existingUser = \App\Models\User::where('email', $employee->email)->first();

            if ($existingUser) {
                // Link to existing user
                $employee->user_id = $existingUser->id;
                $employee->save();

                // Ensure the role is assigned
                if (!$existingUser->hasRole($request->role)) {
                    $existingUser->assignRole($request->role);
                }

                return redirect()->back()
                    ->with('success', "User account linked successfully! The employee can now login with their email ({$employee->email}) and existing password.");
            }

            // Create new user account
            $user = \App\Models\User::create([
                'name' => $employee->full_name,
                'email' => $employee->email,
                'password' => \Illuminate\Support\Facades\Hash::make('Welcome123!'),
                'password_changed_at' => null,
                'password_expires_at' => now()->addDays(7), // Expires in 7 days
                'email_verified_at' => now(),
            ]);

            // Assign role
            $user->assignRole($request->role);

            // Link employee to user
            $employee->user_id = $user->id;
            $employee->save();

            // Log this action
            \App\Models\SecurityAuditLog::logEvent(
                \App\Models\SecurityAuditLog::EVENT_USER_CREATED,
                $user->email,
                $user->id,
                "User account created for employee {$employee->employee_number} via Employee Management",
                [
                    'employee_id' => $employee->id,
                    'employee_number' => $employee->employee_number,
                    'role' => $request->role,
                    'created_by' => auth()->user()->email,
                ],
                \App\Models\SecurityAuditLog::SEVERITY_INFO
            );

            return redirect()->back()
                ->with('success', "User account created successfully! Login credentials: Email: {$user->email}, Password: Welcome123! (expires in 7 days)");

        } catch (\Exception $e) {
            return redirect()->back()
                ->with('error', 'Failed to create user account: ' . $e->getMessage());
        }
    }

    public function destroy(Employee $employee): RedirectResponse
    {
        $this->authorize('delete', $employee);
        $employee->delete();
        return redirect()->route('tenant.modules.human_resources.employees.index')->with('success', 'Employee deleted successfully.');
    }
}
